### ISSUE TITLE
Seeking new maintainer!

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.translate#1]
This package is not being actively maintained. If you're interested in contributing or taking over, please express your interest here.

**Comment by antoine-sachet** [comment]
I am happy to start maintaining this package.

@MarkEdmondson1234 -- sorry, forgot this one! It is also language related so would make sense to add to the "aws text" group.

**Comment by MarkEdmondson1234** [comment]
@antoine-sachet ok cool!
